from psycopg import connect
from psycopg.rows import dict_row
import sys

sys.path.insert(0, "/root/observer")
from incident_correlator import process_signal

from app.core.settings import settings
DATABASE_URL = settings.DATABASE_URL
RECENT_WINDOW_MINUTES = 10


def fetch_services(cur):
    cur.execute("""
    SELECT DISTINCT service_name
    FROM service_monitor_log
    ORDER BY service_name
    """)
    return cur.fetchall()


def fetch_last_real_result(cur, service_name):
    cur.execute(f"""
    SELECT result_status, notes, created_at
    FROM service_monitor_log
    WHERE service_name = %s
      AND result_status IN ('success','failed')
      AND created_at > now() - interval '{RECENT_WINDOW_MINUTES} minutes'
    ORDER BY created_at DESC
    LIMIT 1
    """, (service_name,))
    return cur.fetchone()


def fetch_criticality(cur, service_name):
    cur.execute("""
    SELECT criticality
    FROM service_criticality
    WHERE service_name = %s
    """, (service_name,))
    row = cur.fetchone()
    if not row:
        return "unknown"
    return row["criticality"]


def interpret_health(result_status, notes):
    notes = (notes or "").lower()

    if result_status == "success":
        return "OK"

    if result_status == "failed":
        if "allowlist" in notes or "not allowlisted" in notes:
            return "POLICY_BLOCKED"
        return "EXECUTION_FAILED"

    return "UNKNOWN"


def governance_state(criticality, health):
    if health == "OK":
        return f"{criticality.upper()}_OK"

    if health == "EXECUTION_FAILED":
        return f"{criticality.upper()}_EXECUTION_FAILED"

    if health == "POLICY_BLOCKED":
        return f"{criticality.upper()}_POLICY_BLOCKED"

    return f"{criticality.upper()}_UNKNOWN"


def compute_severity(gov_state):
    if gov_state.startswith("CORE_OK"):
        return "INFO"

    if gov_state.startswith("SUPPORTING_OK"):
        return "INFO"

    if gov_state.startswith("TEST_OK"):
        return "INFO"

    if gov_state.startswith("CORE_EXECUTION_FAILED"):
        return "CRITICAL"

    if gov_state.startswith("SUPPORTING_EXECUTION_FAILED"):
        return "HIGH"

    if gov_state.startswith("TEST_EXECUTION_FAILED"):
        return "WARN"

    if gov_state.startswith("CORE_POLICY_BLOCKED"):
        return "HIGH"

    if gov_state.startswith("SUPPORTING_POLICY_BLOCKED"):
        return "WARN"

    if gov_state.startswith("TEST_POLICY_BLOCKED"):
        return "INFO"

    return "UNKNOWN"


def incident_class_from_severity(severity):
    if severity == "CRITICAL":
        return "CORE_SERVICE_FAILURE"

    if severity == "HIGH":
        return "HIGH_IMPACT_SERVICE"

    if severity == "WARN":
        return "SUPPORTING_SERVICE_ISSUE"

    return None


def build_signal(service_name, severity, gov_state, last):
    incident_class = incident_class_from_severity(severity)
    if not incident_class:
        return None

    result_status = (last.get("result_status") or "").strip()
    notes = (last.get("notes") or "").strip()
    created_at = last.get("created_at")

    description = (
        f"Generated by service_monitor_trigger_writer from recent service_monitor_log. "
        f"gov_state={gov_state}, result_status={result_status}, created_at={created_at}, notes={notes}"
    )

    return {
        "incident_class": incident_class,
        "title": f"{incident_class}: {service_name}",
        "description": description,
        "source_type": "service_monitor_trigger_writer",
        "source_ref": f"service_monitor_trigger_writer:{service_name}",
        "entity_type": "service",
        "entity_name": service_name,
        "severity": severity,
        "evidence_type": "service_monitor_trigger_writer",
        "evidence_ref": f"service_monitor_trigger_writer:{service_name}",
        "summary": f"{service_name} mapped to {incident_class} from {gov_state}",
    }


def main():
    emitted = 0
    suppressed = 0

    with connect(DATABASE_URL, row_factory=dict_row) as conn:
        with conn.cursor() as cur:
            services = fetch_services(cur)

            print("\nSERVICE MONITOR TRIGGER WRITER\n")

            for s in services:
                name = s["service_name"]

                last = fetch_last_real_result(cur, name)
                if not last:
                    suppressed += 1
                    print(name, "| no recent real result → suppressed")
                    continue

                criticality = fetch_criticality(cur, name)

                health = interpret_health(
                    last["result_status"],
                    last["notes"]
                )

                gov = governance_state(
                    criticality,
                    health
                )

                severity = compute_severity(gov)

                if severity == "INFO":
                    suppressed += 1
                    print(name, "| severity INFO → ignored")
                    continue

                signal = build_signal(name, severity, gov, last)
                if not signal:
                    suppressed += 1
                    print(name, "| no incident signal generated → suppressed")
                    continue

                incident_id = process_signal(signal)
                emitted += 1
                print(name, "| severity:", severity, "| incident emitted:", incident_id)

    print()
    print("emitted:", emitted)
    print("suppressed:", suppressed)


if __name__ == "__main__":
    main()
